Refactored the location of package management
lambdal-support/lambda-public-tools pull request #2
Opened 2024-06-26 17:26 UTC by ryaeng

Package management was being done before commands were run. I thought it best to condense this within the bug report. I did this by performing the following:
- Creating an array of utilities we are installing
- Iterating over this array and creating an array of utilities pending install
- Install all of the utilities at once as opposed to doing them one a at a time

My aim was to make this easier to read, more modular, and to reduce the time it takes to run the bug report.

2024-06-28 16:36 UTC, bryangwin requested changes
I would get rid of this. 


`        echo "$u could not be found, pending install."
`

We want the process to be seamless for the customer and have everything happening in background.

```
for u in ${utilities[@]}; do
    if ! command -v $u >/dev/null 2>&1; then
        pending_install_utilities+=($u)
    fi
done
```

2024-07-08 21:45 UTC, bryangwin commented
Additionally the commands are not the same as the apps that need to be installed so there needs to be an associative array like this:
```
# Declare an associative array for utilities and their packages
declare -A utilities
utilities=(
    ["smartctl"]="smartmontools"
    ["ibstat"]="infiniband-diags"
    ["ipmitool"]="ipmitool"
    ["sensors"]="lm-sensors"
    ["iostat"]="sysstat"
    ["lshw"]="lshw"
)

pending_install_packages=()

# Iterate through utilities and create an array of packages pending install
for u in "${!utilities[@]}"; do
    if ! command -v $u >/dev/null 2>&1; then
        pending_install_packages+=("${utilities[$u]}")
    fi
done
```

2024-09-05 16:42 UTC, lambdajosh commented
@bryangwin @ryaeng 
Thoughts on package management:

I would like to suggest we default to _**not**_ install packages on hosts.

We are seeing more and more cases where the lambda-bug-report.sh script is being requested to run on Private Cloud clusters; even in some cases where the host does not have gpus.

As a general practice, we refrain from installing any new packages in customer environments as they can sometimes have deleterious effects on the cluster and introduce inconsistencies in node package lists across the cluster.

A solution could be to run the script with a flag which enables package installs:
`lambda-bug-report.sh --install-utils`

2025-02-08 10:49 UTC, qskwood commented
#13 is an attempt to address the concerns @lambdajosh provided here as well as to begin going after the general premise of making tool installation more maintainable and readable like what @ryaeng was suggesting.

2025-04-21 20:56 UTC, bryangwin commented
Closing this as it was addressed in #13

2025-04-21 20:56 UTC, closed without merging